import { db } from './db';
import { SETTINGS_ID, type Exercise, type Gym, type Settings } from './schema';
import { newId } from '@/lib/ids';
import { nowIso } from '@/lib/dates';

/**
 * Shape of a row in seed.data.json, which is generated by scripts/build-seed.ts.
 * It deliberately carries no sync fields — those are stamped on insert.
 */
type SeedExercise = Omit<Exercise, keyof import('./schema').SyncFields>;

/**
 * Loaded on demand rather than imported at the top level.
 *
 * The seed file is ~430KB and is read exactly once, on first run. A static
 * import would put all of it in the main bundle and make every subsequent
 * cold start pay for data the app will never look at again.
 */
async function loadSeedExercises(): Promise<SeedExercise[]> {
  const module = await import('./seed.data.json');
  return module.default as unknown as SeedExercise[];
}

function syncFields() {
  const now = nowIso();
  return { user_id: null, created_at: now, updated_at: now, deleted_at: null };
}

/**
 * The gym you get before configuring anything: assume a commercial gym with
 * everything, so nothing is filtered out until the user says otherwise.
 */
function defaultGym(): Gym {
  return {
    id: newId(),
    name: 'My gym',
    equipment_available: [
      'barbell', 'dumbbell', 'kettlebell', 'cable', 'machine',
      'bands', 'bodyweight', 'ez_bar', 'exercise_ball', 'medicine_ball', 'other',
    ],
    bar_weights: [20, 15, 10],
    plates_available: [25, 20, 15, 10, 5, 2.5, 1.25],
    is_default: true,
    ...syncFields(),
  };
}

function defaultSettings(gymId: string): Settings {
  return {
    id: SETTINGS_ID,
    units: 'kg',
    default_gym_id: gymId,
    mode: 'beginner',
    default_rest_seconds: 120,
    sound_on: true,
    vibrate_on: true,
    last_synced_at: null,
    ...syncFields(),
  };
}

/**
 * Populates an empty database. Safe to call on every start: it does nothing if
 * exercises already exist, so it never fights the user's own edits.
 */
export async function seedIfEmpty(): Promise<void> {
  const count = await db.exercises.count();
  if (count > 0) return;

  const seedExercises = await loadSeedExercises();
  const gym = defaultGym();
  await db.transaction('rw', db.exercises, db.gyms, db.settings, async () => {
    await db.exercises.bulkAdd(seedExercises.map((ex) => ({ ...ex, ...syncFields() })));
    await db.gyms.add(gym);
    const existing = await db.settings.get(SETTINGS_ID);
    if (!existing) await db.settings.add(defaultSettings(gym.id));
  });
}

/**
 * Refreshes seeded exercise metadata from a newer seed file.
 *
 * Matches on `source_id` and preserves the existing row's UUID, so workout
 * history that references an exercise keeps pointing at it. User-authored
 * fields — `setup_notes`, `increment_kg` — are never overwritten, and custom
 * exercises are left alone entirely.
 */
export async function refreshSeedExercises(): Promise<{ added: number; updated: number }> {
  const seedExercises = await loadSeedExercises();
  let added = 0;
  let updated = 0;

  await db.transaction('rw', db.exercises, async () => {
    const existing = await db.exercises.toArray();
    const bySourceId = new Map(
      existing.filter((ex) => ex.source_id !== null).map((ex) => [ex.source_id!, ex]),
    );

    for (const incoming of seedExercises) {
      const current = incoming.source_id ? bySourceId.get(incoming.source_id) : undefined;
      if (!current) {
        await db.exercises.add({ ...incoming, ...syncFields() });
        added += 1;
        continue;
      }
      await db.exercises.update(current.id, {
        name: incoming.name,
        primary_muscle: incoming.primary_muscle,
        secondary_muscles: incoming.secondary_muscles,
        equipment: incoming.equipment,
        movement_pattern: incoming.movement_pattern,
        is_compound: incoming.is_compound,
        is_unilateral: incoming.is_unilateral,
        experience_level: incoming.experience_level,
        fatigue_cost: incoming.fatigue_cost,
        demo_url: incoming.demo_url,
        // setup_notes and increment_kg are the user's, not the dataset's.
        updated_at: nowIso(),
        deleted_at: null,
      });
      updated += 1;
    }
  });

  return { added, updated };
}

/**
 * Wipes every local table and reseeds from scratch. Destroys all workout
 * history — development helper only, never wired to a casual tap.
 */
export async function wipeAndReseed(): Promise<void> {
  await db.transaction(
    'rw',
    [
      db.exercises, db.gyms, db.routines, db.routine_exercises, db.workouts,
      db.workout_exercises, db.sets, db.plans, db.body_metrics, db.settings,
      db.outbox, db.keepalive,
    ],
    async () => {
      await Promise.all([
        db.exercises.clear(), db.gyms.clear(), db.routines.clear(),
        db.routine_exercises.clear(), db.workouts.clear(), db.workout_exercises.clear(),
        db.sets.clear(), db.plans.clear(), db.body_metrics.clear(),
        db.settings.clear(), db.outbox.clear(), db.keepalive.clear(),
      ]);
    },
  );
  await seedIfEmpty();
}
